<a href="https://colab.research.google.com/github/abdulsamadkhan/Tutorial/blob/main/Basic_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic functionality of RNN

##Preprocessing the text for RNN
The provided Python code performs a series of steps to download and preprocess a text file, create mappings for characters to their indices and vice versa, create subsequences of a specified length, batch those subsequences, and convert them into TensorFlow tensors. Here's a detailed explanation of each part of the code:

1. **Importing Libraries**:
   - `import requests`: This library is used to send HTTP requests and retrieve the text file from a given URL.
   - `import tensorflow as tf`: TensorFlow is imported for creating and manipulating tensors, which are used for neural network training and other numerical operations.
   - `import string`: The `string` module is imported, but it is not used in the provided code.

2. **Step 1: Download and Read a Text File (`download_and_read_text_file`)**:
   - The `download_and_read_text_file` function takes a URL as input and downloads the text file from that URL.
   - It checks the HTTP response status code (200 for success) and converts the text to lowercase.
   - If successful, the function returns the downloaded text.

3. **Step 2: Create Character-to-Index and Index-to-Character Dictionaries (`create_char_mappings`)**:
   - The `create_char_mappings` function takes the downloaded text as input.
   - It extracts unique characters from the text and creates two dictionaries:
     - `char_to_index`: Maps characters to their respective indices.
     - `index_to_char`: Maps indices to their corresponding characters.
   - These dictionaries are essential for encoding and decoding text during text processing and modeling.

4. **Step 3: Create Subsequences of a Specified Length (`create_subsequences`)**:
   - The `create_subsequences` function takes the downloaded text and a specified sequence length as input.
   - It generates subsequences of characters by sliding a window of the given length over the text.
   - For each subsequence, it creates an input sequence and a target sequence, where the target sequence is one character ahead of the input sequence.
   - These subsequences are used for training sequence models like RNNs.

5. **Step 4: Batch the Subsequences (`batch_sequences`)**:
   - The `batch_sequences` function takes a list of subsequences and a batch size as input.
   - It groups the subsequences into batches of the specified size.

6. **Step 5: Create Input and Output Sequences and Convert to Tensors (`create_input_output_tensors` and `create_tensor_dataset`)**:
   - The `create_input_output_tensors` function takes a subsequence and the character-to-index dictionary as input.
   - It converts input and target subsequences into tensors with characters mapped to their indices.
   - The `create_tensor_dataset` function processes multiple subsequences, converting them into TensorFlow tensors.

7. **Downloading a File with URL**:
   - A file URL (`file_url`) is provided as an example, and the `download_and_read_text_file` function is called to download and read the text from that URL.
   - You should replace the example URL with the actual URL of the text file you want to process.

This code snippet sets up the initial steps for processing and preparing text data for further analysis or modeling, such as training a character-level language model. The downloaded text is converted to lowercase, and character-to-index mappings are created for encoding and decoding the text during model training. Additionally, subsequences are generated, batched, and converted into TensorFlow tensors, which can be useful for training neural network models.

In [2]:
import requests
import tensorflow as tf
import string

# Step 1: Download and read a text file
def download_and_read_text_file(url):
    response = requests.get(url)
    if response.status_code == 200:
        text = response.text
        return text.lower()
    else:
        raise Exception(f"Failed to download the file from {url}")

# Step 2: Create a character-to-index and index-to-character dictionary
def create_char_mappings(text):
    unique_chars = list(set(text))
    char_to_index = {char: idx for idx, char in enumerate(unique_chars)}
    index_to_char = {idx: char for idx, char in enumerate(unique_chars)}
    return char_to_index, index_to_char

# Step 3: Create subsequences of a specified length
def create_subsequences(text, sequence_length):
    sequences = []
    for i in range(0, len(text) - sequence_length, sequence_length):
        input_seq = text[i:i + sequence_length]
        target_seq = text[i + 1:i + sequence_length + 1]
        sequences.append((input_seq, target_seq))
    return sequences

# Step 4: Batch the subsequences
def batch_sequences(sequences, batch_size):
    batches = []
    for i in range(0, len(sequences), batch_size):
        batch = sequences[i:i + batch_size]
        batches.append(batch)
    return batches

# Step 5: Create input and output sequences
def create_input_output_tensors(sequence, char_to_index):
    input_sequence, target_sequence = sequence
    input_tensor = [char_to_index[char] for char in input_sequence]
    target_tensor = [char_to_index[char] for char in target_sequence]
    return input_tensor, target_tensor

# Step 5: Convert subsequences to TensorFlow tensors
def create_tensor_dataset(sequences, char_to_index):
    input_tensors = []
    target_tensors = []
    for sequence in sequences:
        input_seq, target_seq = sequence
        input_tensor = tf.convert_to_tensor([char_to_index[char] for char in input_seq], dtype=tf.int32)
        target_tensor = tf.convert_to_tensor([char_to_index[char] for char in target_seq], dtype=tf.int32)
        input_tensors.append(input_tensor)
        target_tensors.append(target_tensor)
    return input_tensors, target_tensors

# downloading a file with URL
file_url = 'https://example-files.online-convert.com/document/txt/example.txt'  # Replace with the actual URL
text = download_and_read_text_file(file_url)



In [3]:
char_to_index, index_to_char = create_char_mappings(text)
char_to_index

{'z': 0,
 'c': 1,
 'i': 2,
 'b': 3,
 ' ': 4,
 'm': 5,
 '-': 6,
 '2': 7,
 '.': 8,
 'v': 9,
 'a': 10,
 'u': 11,
 '/': 12,
 ',': 13,
 '#': 14,
 'h': 15,
 ')': 16,
 'p': 17,
 'w': 18,
 '1': 19,
 'x': 20,
 'n': 21,
 'g': 22,
 'q': 23,
 'l': 24,
 '\n': 25,
 'y': 26,
 '"': 27,
 '(': 28,
 '4': 29,
 't': 30,
 'e': 31,
 '0': 32,
 'k': 33,
 's': 34,
 'r': 35,
 'j': 36,
 ':': 37,
 ';': 38,
 'f': 39,
 'o': 40,
 'd': 41,
 '_': 42}

In [4]:
sequence_length = 20
subsequences = create_subsequences(text, sequence_length)
subsequences


[('txt test file\npurpos', 'xt test file\npurpose'),
 ('e: provide example o', ': provide example of'),
 ('f this file type\ndoc', ' this file type\ndocu'),
 ('ument file type: txt', 'ment file type: txt\n'),
 ('\nversion: 1.0\nremark', 'version: 1.0\nremark:'),
 (':\n\nexample content:\n', '\n\nexample content:\nt'),
 ('the names "john doe"', 'he names "john doe" '),
 (' for males, "jane do', 'for males, "jane doe'),
 ('e" or "jane roe" for', '" or "jane roe" for '),
 (' females, or "jonnie', 'females, or "jonnie '),
 (' doe" and "janie doe', 'doe" and "janie doe"'),
 ('" for children, or j', ' for children, or ju'),
 ('ust "doe" non-gender', 'st "doe" non-gender-'),
 ('-specifically are us', 'specifically are use'),
 ('ed as placeholder na', 'd as placeholder nam'),
 ('mes for a party whos', 'es for a party whose'),
 ('e true identity is u', ' true identity is un'),
 ('nknown or must be wi', 'known or must be wit'),
 ('thheld in a legal ac', 'hheld in a legal act'),
 ('tion, case, or

# New Section

In [5]:
batch_size = 2
batches = batch_sequences(subsequences, batch_size)
input, target=batches[0][0]
#print(input)
#print("-----")
#print(target)
input_seq, target_seq = batches[0][0]
input_seq

'txt test file\npurpos'

In [6]:
input_tensor, target_tensor = create_input_output_tensors((input_seq, target_seq), char_to_index)
len(input_tensor)

20

In [7]:
# make the whole dataste as tensor
input_tensors, target_tensors = create_tensor_dataset(subsequences, char_to_index)
input_tensors[0].shape

TensorShape([20])

https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/

# RNN model
Certainly! The provided Python code defines a recurrent neural network (RNN) model using TensorFlow's Keras API. This code snippet includes model architecture definition, hyperparameter settings, model creation, and compilation. Here's a detailed explanation of each part of the code:

1. **Define the RNN Model (`SimpleRNNModel`)**:
   - The code defines a custom RNN model named `SimpleRNNModel` that inherits from `tf.keras.Model`.
   - In the constructor (`__init__` method), the following layers are defined:
     - `embedding`: An embedding layer that maps input tokens to dense vectors. The size of the vocabulary (`vocab_size`) and the embedding dimension (`embedding_dim`) are provided as parameters.
     - `rnn`: A SimpleRNN layer with `rnn_units` units. It returns sequences (`return_sequences=True`) to provide sequences of outputs at each time step. The `recurrent_initializer` is set to 'glorot_uniform' for weight initialization.
     - `dense`: A dense layer with `vocab_size` units, which is used to produce the final output.

2. **Hyperparameters**:
   - Hyperparameters for the model are defined:
     - `vocab_size`: The size of the vocabulary. It's set based on the length of a character-to-index mapping (not shown in the provided code).
     - `embedding_dim`: The dimension of the word embeddings.
     - `rnn_units`: The number of units (neurons) in the RNN layer.
     - `sequence_length`: The length of input sequences. You can adjust this value according to your dataset.

3. **Create the Model**:
   - The RNN model is created by instantiating the `SimpleRNNModel` class with the specified hyperparameters. The resulting model is stored in the `model` variable.

4. **Compile the Model**:
   - The model is compiled to prepare it for training. The following settings are specified during compilation:
     - `optimizer='adam'`: The Adam optimizer is used for gradient descent optimization.
     - `loss='sparse_categorical_crossentropy'`: This is a common choice for text classification tasks where the target values are integers representing class labels.

This code sets up a custom RNN model for text processing tasks. You can use this model for tasks like text generation, sentiment analysis, or any NLP-related problem where sequence data is involved. Before training the model, you would typically need to prepare your data, tokenize it, and convert it to a format that the model can accept. Additionally, you may need to define training loops, preprocess data, and fit the model to your specific dataset.

In [13]:
# Define the RNN model with one hidden layer
class SimpleRNNModel(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, rnn_units):
        super(SimpleRNNModel, self).__init__()
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
        self.rnn = tf.keras.layers.SimpleRNN(rnn_units, return_sequences=True, recurrent_initializer='glorot_uniform')
        self.dense = tf.keras.layers.Dense(vocab_size)

    def call(self, inputs):
        x = self.embedding(inputs)
        x = self.rnn(x)
        output = self.dense(x)
        return output

# Hyperparameters
vocab_size = len(char_to_index)
embedding_dim = 256
rnn_units = 512
sequence_length = 50  # You can adjust this based on your dataset

# Create the model
model = SimpleRNNModel(vocab_size, embedding_dim, rnn_units)

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')


#Training RNN Loop

1. **`train_rnn_model` Function**:
   - This function is designed to train an RNN model. It takes the following parameters:
     - `input_tensors`: List of input tensors (sequences of input data).
     - `target_tensors`: List of target tensors (sequences of target data).
     - `epochs` (optional, default: 10): Number of training epochs (complete passes through the dataset).
     - `batch_size` (optional, default: 32): Mini-batch size for training.

2. **Training Loop**:
   - The function starts with a loop over the specified number of `epochs`. During each epoch, the entire dataset is processed in mini-batches.

3. **Mini-Batch Loop**:
   - Within each epoch, there is another loop that iterates over mini-batches of data.
   - The loop variable `i` is used to keep track of the starting index of each mini-batch.

4. **Print Current Batch Index**:
   - For monitoring and debugging purposes, the code prints the current batch index (`i`) to the console. This helps you keep track of the progress during training.

5. **Extract Mini-Batch Data**:
   - Inside the mini-batch loop, the code extracts a mini-batch of input and target tensors.
   - `x` contains a stack of input tensors, and `y` contains a stack of corresponding target tensors.

6. **Model Training (Fitting)**:
   - The mini-batch of input (`x`) and target (`y`) tensors is used to train (fit) the RNN model using the `model.fit` method. The `batch_size` and `verbose` parameters are specified during training.
   - `batch_size` determines the size of the mini-batch used for gradient updates.
   - `verbose=2` means that training progress is printed to the console for each epoch, including loss and other metrics.

This code essentially sets up a training loop for an RNN model, enabling you to train the model on sequential data stored in input and target tensors. The training process involves iterating over the dataset multiple times (controlled by `epochs`) and updating the model's weights to minimize the specified loss function. The model used for training should be defined and compiled separately.

In [ ]:
def train_rnn_model(input_tensors, target_tensors, epochs=10, batch_size=32):
  for epoch in range(epochs):
    for i in range(0, len(input_tensors) - batch_size, batch_size):
      print(i)
      x = tf.stack(input_tensors[i:i + batch_size], axis=0)
      y = tf.stack(target_tensors[i:i + batch_size], axis=0)
      model.fit(x, y, batch_size=batch_size, verbose=2)

In [ ]:
train_rnn_model(input_tensors, target_tensors, epochs=1, batch_size=10)

0
1/1 - 0s - loss: 5.7145 - 38ms/epoch - 38ms/step
10
1/1 - 0s - loss: 4.7206 - 53ms/epoch - 53ms/step
20
1/1 - 0s - loss: 4.3070 - 41ms/epoch - 41ms/step
30
1/1 - 0s - loss: 3.9285 - 41ms/epoch - 41ms/step
40
1/1 - 0s - loss: 4.0939 - 44ms/epoch - 44ms/step
50
1/1 - 0s - loss: 3.8180 - 52ms/epoch - 52ms/step
60
1/1 - 0s - loss: 4.7247 - 47ms/epoch - 47ms/step
70
1/1 - 0s - loss: 3.8631 - 38ms/epoch - 38ms/step
80
1/1 - 0s - loss: 4.0075 - 49ms/epoch - 49ms/step
90
1/1 - 0s - loss: 4.8541 - 41ms/epoch - 41ms/step
100
1/1 - 0s - loss: 4.4273 - 44ms/epoch - 44ms/step
110
1/1 - 0s - loss: 7.1211 - 40ms/epoch - 40ms/step


In [ ]:
char_to_index

{'2': 0,
 't': 1,
 'n': 2,
 'r': 3,
 '_': 4,
 'l': 5,
 '/': 6,
 ':': 7,
 '.': 8,
 'g': 9,
 'h': 10,
 'k': 11,
 '-': 12,
 '"': 13,
 'd': 14,
 'p': 15,
 'v': 16,
 's': 17,
 '0': 18,
 'x': 19,
 'w': 20,
 ' ': 21,
 'z': 22,
 'f': 23,
 'j': 24,
 ';': 25,
 'a': 26,
 ')': 27,
 'y': 28,
 '\n': 29,
 'q': 30,
 '#': 31,
 'i': 32,
 'e': 33,
 'c': 34,
 '(': 35,
 'o': 36,
 '4': 37,
 ',': 38,
 'b': 39,
 '1': 40,
 'u': 41,
 'm': 42}

#Generating the text from RNN Model

1. **The function `generate_text`** is designed to generate text using a trained model. It takes the following parameters:
   - `model`: The trained neural network model used for text generation.
   - `start_string`: The initial text that serves as a seed for text generation.
   - `num_generate`: The number of characters to generate beyond the start string.

2. The code converts the `start_string` to lowercase and initializes some variables for text generation.

3. It iteratively generates characters:
   - The function loops 5 times to generate 5 characters. You can adjust this number as needed.
   - The model is used to make predictions based on the input evaluation (`input_eval`).

4. In each iteration, the following steps occur:
   - The shape of the predictions from the model is printed.
   - The predictions are squeezed to remove the batch dimension for easier handling.
   - A character ID is sampled from the predictions using random sampling.
   - The ID of the predicted character is printed.
   - The predicted character's ID is used to prepare the next input for text generation.

5. The generated characters are appended to the `text_generated` list.

6. Finally, the generated text is returned by concatenating the `start_string` with the characters generated in the loop.

7. The generated text is printed to the console.

This code is used for generating text sequences based on a trained language model, where the model takes a seed text and predicts the next characters in the sequence, making it useful for various natural language generation tasks.

In [ ]:
# Generate text using the trained model
def generate_text(model, start_string,  num_generate):
  start_string = start_string.lower()
  default_index = -1
  input_eval = [char_to_index.get(s,-1) for s in start_string]
  print(input_eval)
  input_eval = tf.expand_dims(input_eval, 0)
  print(input_eval)
  text_generated = []

  for _ in range(5):
    predictions = model(input_eval)
    print(predictions.shape)
    predictions = tf.squeeze(predictions, 0)
    print(predictions.shape)

    predicted_id = tf.random.categorical(predictions, num_samples=1)[-1, 0].numpy()
    print(predicted_id)
    input_eval = tf.expand_dims([predicted_id], 0)
    print(input_eval)
    text_generated.append(index_to_char[predicted_id])
  return start_string + ''.join(text_generated)


# Generate text
generated_text = generate_text(model, start_string="The quick brown", num_generate=5)
print(generated_text)


[1, 10, 33, 21, 30, 41, 32, 34, 11, 21, 39, 3, 36, 20, 2]
tf.Tensor([[ 1 10 33 21 30 41 32 34 11 21 39  3 36 20  2]], shape=(1, 15), dtype=int32)
(1, 15, 43)
(15, 43)
24
tf.Tensor([[24]], shape=(1, 1), dtype=int32)
(1, 1, 43)
(1, 43)
13
tf.Tensor([[13]], shape=(1, 1), dtype=int32)
(1, 1, 43)
(1, 43)
0
tf.Tensor([[0]], shape=(1, 1), dtype=int32)
(1, 1, 43)
(1, 43)
30
tf.Tensor([[30]], shape=(1, 1), dtype=int32)
(1, 1, 43)
(1, 43)
29
tf.Tensor([[29]], shape=(1, 1), dtype=int32)
the quick brownj"2q

